# Generated by Django 2.0.5 on 2018-10-10 19:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('prescription_id', models.AutoField(primary_key=True, serialize=False)),
                ('dossage', models.IntegerField(choices=[(0, '200mg'), (1, '400mg'), (2, '600mg'), (3, '800mg'), (4, '1g'), (5, '1 tablet'), (6, '2 tablets'), (7, '3 tablets'), (8, '4 tablets')], default=0)),
                ('frequency', models.IntegerField(choices=[(0, 'Twice A Day'), (1, 'Once A Day'), (2, 'Once In Two Days'), (3, 'Once A Week'), (4, 'Twice A Week'), (5, 'Once A Month'), (6, 'Twice A Month')], default=0)),
                ('drug', models.IntegerField(choices=[(0, 'Famotidine'), (1, 'Ranitidine'), (2, 'Esomeprazole'), (3, 'Aspirin'), (4, 'Ibuprofen'), (5, 'Diphenhydramine Hydrochloride'), (6, 'Hydroxyzine'), (7, 'Cetirizine Hydrochloride'), (8, 'Amoxicillin')], default=0)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(default=django.utils.timezone.now)),
                ('pre_doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='doctor_prescriptions', to=settings.AUTH_USER_MODEL)),
                ('pre_patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patient_prescriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['start_date', 'end_date'],
            },
        ),
    ]
