# Generated by Django 2.0.5 on 2018-10-10 19:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appointment', '0002_appointment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['app_doctor', 'date', 'timeslot']},
        ),
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('app_doctor', 'date', 'timeslot')},
        ),
    ]
