# Generated by Django 2.0.5 on 2018-10-08 21:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_prescription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='appointment',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='dosage',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='drug_name',
        ),
        migrations.AddField(
            model_name='prescription',
            name='doctor',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='appointment.Doctor'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='dossage',
            field=models.IntegerField(choices=[(0, '200mg'), (1, '400mg'), (2, '600mg'), (3, '800mg'), (4, '1g'), (5, '1 tablet'), (6, '2 tablets'), (7, '3 tablets'), (8, '4 tablets')], default=10),
        ),
        migrations.AddField(
            model_name='prescription',
            name='drug',
            field=models.IntegerField(choices=[(0, 'Famotidine'), (1, 'Ranitidine'), (2, 'Esomeprazole'), (3, 'Aspirin'), (4, 'Ibuprofen'), (5, 'Diphenhydramine Hydrochloride'), (6, 'Hydroxyzine'), (7, 'Cetirizine Hydrochloride'), (8, 'Amoxicillin')], default=10),
        ),
        migrations.AddField(
            model_name='prescription',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='prescription',
            name='frequency',
            field=models.IntegerField(choices=[(0, 'Twice A Day'), (1, 'Once A Day'), (2, 'Once In Two Days'), (3, 'Once A Week'), (4, 'Twice A Week'), (5, 'Once A Month'), (6, 'Twice A Month')], default=10),
        ),
        migrations.AddField(
            model_name='prescription',
            name='patient',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='appointment.Patient'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('patient', 'doctor', 'date', 'timeslot')},
        ),
    ]
