# Generated by Django 2.0.5 on 2018-10-08 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_auto_20181008_2141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prescription',
            old_name='dossage',
            new_name='dossageMark',
        ),
        migrations.RenameField(
            model_name='prescription',
            old_name='drug',
            new_name='drugMark',
        ),
        migrations.RenameField(
            model_name='prescription',
            old_name='frequency',
            new_name='frequencyMark',
        ),
    ]
