# Generated by Django 2.0.5 on 2018-10-11 01:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_auto_20181010_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='pre_doctor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='doctor_prescriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='pre_patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='patient_prescriptions', to=settings.AUTH_USER_MODEL),
        ),
    ]
