# Generated by Django 2.0.5 on 2018-10-08 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0004_auto_20181008_2253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prescription',
            old_name='dossageMark',
            new_name='dossage',
        ),
        migrations.RenameField(
            model_name='prescription',
            old_name='drugMark',
            new_name='drug',
        ),
        migrations.RenameField(
            model_name='prescription',
            old_name='frequencyMark',
            new_name='frequency',
        ),
    ]
