# Generated by Django 2.0.5 on 2018-10-11 01:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0004_auto_20181011_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='app_doctor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='doctor_appointments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='app_patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='patient_appointments', to=settings.AUTH_USER_MODEL),
        ),
    ]
